name: 'Test sync stuff'
description: "Sync stuff"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Sync
      shell: bash
      run: "node src/javascript/dist/index.js"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    - name: Run GitHub File Sync
      uses: BetaHuhn/repo-file-sync-action@v1.17.17
      with:
        GH_PAT: ${{ secrets.GH_PAT }}